language: php
php:
  - "7.2"
  - "7.1"
before_install:
  - php /home/travis/.phpenv/versions/5.6/bin/composer.phar self-update
before_script:
  - composer install
script: phpunit --configuration phpunit.xml --coverage-text  
